server:
  port: 8071

spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://47.106.132.130:3306/springcloud?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: 47.106.132.130:8848

rocketmq:
  nameServer: 47.106.132.130:9876